# Dockerfile-based deployment with Laravel, Vite and PHP

services:
  - type: web
    name: composite-risk-explorer
    runtime: docker
    repo: https://github.com/ArtificialIntellicat/composite-risk-explorer-gmi-wri
    region: frankfurt
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
            name: composite-risk-explorer-db
            property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        fromDatabase:
            name: composite-risk-explorer-db
            property: database
      - key: DB_USERNAME
        fromDatabase:
            name: composite-risk-explorer-db
            property: user
      - key: DB_PASSWORD
        fromDatabase:
            name: composite-risk-explorer-db
            property: password

databases:
  - name: composite-risk-explorer-db
    databaseName: composite
    user: explorer
    ipAllowList: []
